### ISSUE TITLE
Mentionner la personne en question

### ISSUE THREAD

**Issue by Alexiscomete** [parlabarbedeMerlin/je-peux-avoir-ton-pseudo-et-tag-discord-Ilingu#1]
**Problème :**
Quand une personne suivi fait un nouveau repo, on ne le voit pas toujours
**Solution :**
Mentionner cette personne

**Comment by Alexiscomete** [comment]
Je pense que l'on reçoit dans ce cas un mail
Si ce n'est pas le cas il faut alors envoyer une invitation de collaboration

**Comment by parlabarbedeMerlin** [comment]
C'est déjà fait

**Comment by Alexiscomete** [comment]
Ok alors je ferme l'issue
